### ISSUE TITLE
Set a higher body size limit

### ISSUE THREAD

**Issue by adgad** [Financial-Times/simple-email-service#1]
Body Parser defaults to a 100kb limit, which is a bit too small for sending some HTML emails

I suppose a sensible limit might be 5-10MB?

https://github.com/expressjs/body-parser

**Comment by geek-caroline** [comment]
Yup, will increase the limit

**Comment by richard-still-ft** [comment]
Worth having a sensible size limit I think. It's only text so a few hundred k should be OK shouldn't it?

**Comment by adgad** [comment]
Agree. So our initial email with ~30 articles = 90kb. Don't think we'd show
more than 100 articles at most, so ~500kb should be reasonable.

On 1 June 2015 at 17:10, richard-still-ft <notifications@github.com> wrote:

> Worth having a sensible size limit I think. It's only text so a few
> hundred k should be OK shouldn't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/simple-email-service/issues/1#issuecomment-107612771>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by syymza** [comment]
Fixed by #5
