### ISSUE TITLE
Add source to Sparkpost metadata

### ISSUE THREAD

**Issue by syymza** [Financial-Times/simple-email-service#7]
The analytics service is not receiving a valid source when messages are sent via Sparkpost.
We handle that in Sendgrid [here](https://github.com/Financial-Times/simple-email-service/blob/9291eea1280b1c38e6521ad3b1020c6bc0c510c6/app/util/restructurer.sendgrid.js#L56), but there is no equivalent line for Sparkpost.

**Comment by geek-caroline** [comment]
Have fixed with related commit.
